### PR TITLE
feat: initial chinese version markdown

### PR DESCRIPTION
**Pull request by A0150315**
It will be slowly improved here.

### CODE REVIEW

**Comment by jojoldu** [comment]
Thanks PR!
I'm watching your commit

I think it's hard to translate everything.

I'll Merge you if you finish it!

**Comment by jojoldu** [comment]
@A0150315 Hi :)

Thanks for the good translation
Can I merge now?

I want to hear your opinion

**Comment by A0150315** [comment]
sorry, i was busy in these days. so, there aren't some progression, i plan to translate it and complete it in this week

**Comment by A0150315** [comment]
> @A0150315 Hi :)
> 
> Thanks for the good translation
> Can I merge now?
> 
> I want to hear your opinion

sorry, i was busy in these days. so, there aren't some progression, i plan to translate it and complete it in this week

**Comment by A0150315** [comment]
@jojoldu i think it can be merged now，lots of companys' names or person names are difficulties in translation，cause i was not familiar with the Korea local cultures, so, some article title needed more person to translate it, but i think,  this translation is enough for the Chinese whom live in Korea

🙃what's your opinion?

**Comment by jojoldu** [comment]
@A0150315 

Good opinion!
I agree with you. :)
Then I'll merge

**Comment by A0150315** [comment]
@jojoldu 😀

**Pull request merged**
